*&---------------------------------------------------------------------*
*& Report Z6WEEK_SEL_EX05
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT Z6WEEK_SEL_EX05.

SELECTION-SCREEN BEGIN OF BLOCK part5 WITH FRAME TITLE text-005.
PARAMETERS p_carrid TYPE spfli-carrid
                    AS LISTBOX VISIBLE LENGTH 20
                    DEFAULT 'LH'.
SELECTION-SCREEN END OF BLOCK part5.

SELECTION-SCREEN BEGIN OF BLOCK part6 WITH FRAME TITLE text-006.
PARAMETERS p01 TYPE spfli-mandt.
PARAMETERS p02 TYPE spfli-carrid.
PARAMETERS p03 TYPE spfli-connid.
PARAMETERS p04 TYPE spfli-countryfr.
PARAMETERS p05 TYPE spfli-cityfrom.
PARAMETERS p06 TYPE spfli-airpfrom.
PARAMETERS p07 TYPE spfli-countryto.
PARAMETERS p08 TYPE spfli-cityto.
PARAMETERS p09 TYPE spfli-airpto.
PARAMETERS p10 TYPE spfli-fltime.
PARAMETERS p11 TYPE spfli-deptime.
PARAMETERS p12 TYPE spfli-arrtime.
PARAMETERS p13 TYPE spfli-distance.
PARAMETERS p14 TYPE spfli-distid.
PARAMETERS p15 TYPE spfli-fltype.
PARAMETERS p16 TYPE spfli-period.
SELECTION-SCREEN END OF BLOCK part6.

SELECTION-SCREEN BEGIN OF BLOCK part7 WITH FRAME TITLE text-007.
PARAMETERS lp01 TYPE spfli-mandt AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp02 TYPE spfli-carrid AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp03 TYPE spfli-connid AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp04 TYPE spfli-countryfr AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp05 TYPE spfli-cityfrom AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp06 TYPE spfli-airpfrom AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp07 TYPE spfli-countryto AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp08 TYPE spfli-cityto AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp09 TYPE spfli-airpto AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp10 TYPE spfli-fltime AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp11 TYPE spfli-deptime AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp12 TYPE spfli-arrtime AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp13 TYPE spfli-distance AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp14 TYPE spfli-distid AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp15 TYPE spfli-fltype AS LISTBOX VISIBLE LENGTH 20.
PARAMETERS lp16 TYPE spfli-period AS LISTBOX VISIBLE LENGTH 20.
SELECTION-SCREEN END OF BLOCK part7.

SELECTION-SCREEN BEGIN OF BLOCK part8 WITH FRAME TITLE text-008.
PARAMETERS sp01 TYPE zscarr-mandt.
PARAMETERS sp02 TYPE zscarr-carrid.
PARAMETERS sp03 TYPE zscarr-carrname.
PARAMETERS sp04 TYPE zscarr-currcode.
PARAMETERS sp05 TYPE zscarr-url.
SELECTION-SCREEN END OF BLOCK part8.

START-OF-SELECTION.
  WRITE : p_carrid.